server:
  port: 8080
spring:
  datasource: 
    druid: 
      url: jdbc:mysql://192.168.0.1:3306/yue_test?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      filter: 
        slf4j:
          enabled: true
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
  redis:
    host: 192.168.0.1
    port: 6379
    database: 1
    timeout: 3000
logging:
  level:
    druid.sql.Statement: DEBUG